#!/usr/bin/env ruby

require 'bundler/setup'
require 'evolvable'

Dir['./examples/*.rb'].each { |f| require f }

population = HelloWorld.new_population(size: 100,
                                       evaluation: { equalize: 0 },
                                       mutation: { probability: 0.6 })
population.evolve
HelloWorld.start_loop(population)

require 'irb'
IRB.start(__FILE__)
